"""How high can the heel spur sit and still catch the robot before it tips?

Two competing requirements. The spur must reach the floor BEFORE the sole-only tipping
angle, or it never carries load and buys nothing. It must also stay off the floor during
walking, or it enlarges the contact patch and kills commanded yaw the way a long sole does
(tools/foot_length_sweep.py). This sweep moves only the spur collision box in the generated
model and measures both ends: static tipping, and commanded yaw / forward speed.
"""
import json,math,sys,tempfile
import xml.etree.ElementTree as E
from pathlib import Path
import numpy as np
R=Path(__file__).resolve().parents[1];sys.path.insert(0,str(R/'cad'));sys.path.insert(0,str(R/'runtime'))
import layout as L
sys.path.insert(0,str(R/'tools'))
SRC=R/'models/micro_cat_14.xml'
def variant(lift_mm,tmp,remove=False):
    tree=E.parse(SRC)
    for geom in list(tree.getroot().iter('geom')):
        if not (geom.get('name') or '').endswith('_foot_spur_collision'):continue
        if remove:
            for parent in tree.getroot().iter('body'):
                if geom in list(parent):parent.remove(geom)
            continue
        pos=[float(v) for v in geom.get('pos').split()]
        pos[2]=pos[2]-(BASE_LIFT-lift_mm)*.001
        geom.set('pos',' '.join(f'{v:.9g}' for v in pos))
    out=Path(tmp)/f'spur_{"none" if remove else lift_mm}.xml';tree.write(out,encoding='unicode');return out
BASE_LIFT=1.0 # mm, as generated by cad/build.py
def engagement(model):
    """Backward tilt at which the spur first reaches the floor, from the model's own geometry.

    The spur is only worth anything if this is SMALLER than the sole-only tipping angle.
    The difference is the margin, and it is thin: report it rather than asserting a fixed
    lift is safe, because it moves whenever the centre of mass moves."""
    import mujoco
    m=mujoco.MjModel.from_xml_path(str(model));d=mujoco.MjData(m)
    d.qpos[:7]=[0,0,.125,1,0,0,0]
    for j in range(m.njnt):
        n=mujoco.mj_id2name(m,mujoco.mjtObj.mjOBJ_JOINT,j)
        if n in L.HOME:d.qpos[m.jnt_qposadr[j]]=L.HOME[n]
    mujoco.mj_forward(m,d)
    def corners(suffix):
        out=[]
        for g in range(m.ngeom):
            n=mujoco.mj_id2name(m,mujoco.mjtObj.mjOBJ_GEOM,g) or ''
            if not n.endswith(suffix):continue
            c=d.geom_xpos[g];M=d.geom_xmat[g].reshape(3,3);sz=m.geom_size[g]
            out+=[c+M@np.array([sx*sz[0],sy*sz[1],sz_*sz[2]]) for sx in(-1,1) for sy in(-1,1) for sz_ in(-1,1)]
        return np.array(out) if out else None
    sole=corners('_foot_collision');spur=corners('_foot_spur_collision')
    if spur is None:return None
    floor=sole[:,2].min();pivot=sole[sole[:,2]<=floor+1e-5][:,0].min()
    rear=spur[spur[:,0].argmin()]
    setback=pivot-rear[0];lift=rear[2]-floor
    return round(math.degrees(math.atan2(lift,setback)),2) if setback>0 else None
if __name__=='__main__':
    from compat_env import Environment
    import tip_study_lib as T
    rows=[]
    with tempfile.TemporaryDirectory() as tmp:
        cases=[('no spur',variant(0,tmp,remove=True))]+[(f'{l} mm',variant(l,tmp)) for l in [0.5,1.0,1.5]]
        for label,model in cases:
            tip=T.study(model)
            def run(cmd,seconds=10.):
                env=Environment(model_path=model);env.reset(seed=0);env.policy.set_vel_cmd(*cmd)
                fell=None
                for _ in range(int(seconds*50)):
                    _,f,_=env.step(env.policy.infer())
                    if f and fell is None:fell=float(env.data.time)
                q=env.data.qpos[3:7]
                yaw=math.atan2(2*(q[0]*q[3]+q[1]*q[2]),1-2*(q[2]**2+q[3]**2))
                return yaw/seconds,float(np.linalg.norm(env.data.qpos[:2]))/seconds,fell
            yaw,_,fell_t=run((0,0,1.0));_,spd,fell_f=run((0.6,0,0))
            eng=engagement(model)
            rows.append(dict(spur_lift=label,tip_aft_deg=tip['tip_aft_deg'],tip_fwd_deg=tip['tip_fwd_deg'],
                engagement_deg=eng,margin_deg=(None if eng is None else round(tip['tip_aft_deg']-eng,2)),
                yaw_rate_at_cmd_1_rad_s=round(yaw,4),speed_at_cmd_0p6_m_s=round(spd,4),
                fell_turning_s=fell_t,fell_forward_s=fell_f))
            print(rows[-1],flush=True)
    (R/'artifacts/heel_spur_sweep.json').write_text(json.dumps(dict(
        scope=' '.join(l.strip() for l in __doc__.strip().split('\n')[2:]),
        note='Only the spur collision box moves; printed parts, masses and joint limits are identical.',
        results=rows),indent=1)+'\n')
